# Generated by Django 5.0.1 on 2024-03-25 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
